<footer class="site-footer">
    <div>
        <strong>Nexora</strong>
        <p>Connecting communities to brighter digital futures.</p>
    </div>

    <p>
        Email:
        <a href="mailto:info@nexora.com">info@nexora.com</a>
    </p>

    <p>
        <a href="https://github.com/dhuwaalghanim/G02-project2" target="_blank">GitHub Repository</a> |
        <a href="https://jira.com" target="_blank">Jira Board</a>
    </p>
</footer>

</body>
</html>